# Generated by Django 4.2.8 on 2023-12-28 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('updated', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('body_post', models.CharField(max_length=200, verbose_name='body_post')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='post_image', variations={'thumb': (200, 200)})),
                ('link', models.CharField(max_length=300, verbose_name='link')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('user_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
