# Generated by Django 4.2.8 on 2023-12-29 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='post_image', variations={'thumb': (200, 200)}),
        ),
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, max_length=300, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
